### PR TITLE
Valparaiso

### PR DESCRIPTION
**Pull request by cornejotux**

### CODE REVIEW

**Comment by mbjones** [comment]
@cornejotux This looks really interesting.  Did you translate all of the training materials?  Rather than master, I think this would be better committed in a branch, and we could consider how to maintain multiple language translations of the content.  Or did you accidentally merge this to the NCEAS master branch?

**Comment by cornejotux** [comment]
Hi Matt,

Sorry about that, I didn't mean to merge it with NCEAS. Maybe you should
remove me as a collaborator to avoid future mistakes.
I haven´t translated it all, I want to take some parts for an RMarkdown
class.
Right now I'm trying to understand how to make events and get the modified
book into a published material but I still can't get it. I guess I made the
merge with NCEAS while trying to.
Can you fix it? I'm concern to make it even worse if I'm trying to myself.

---------------------------------------------------------
Jorge F. Cornejo-Donoso
PhD Marine Science
cornejotux@gmail.com
http://www.jorgecornejo.net

**Comment by mbjones** [comment]
OK, Jorge.  I reverted your merge and now `master` is back to where it started.  I will also remove your commit rights from this repository as you requested.  If you want to create your own repository from your copy, you can use the `git remotes` command to update the connections to remote repositories.

**Comment by cornejotux** [comment]
Thanks and sorry about that.

**Pull request merged**
